# https://github.com/KnpLabs/KnpMenuPartBundle/blob/master/Resources/doc/menu_service.md

services:
    wmc.menu_part.menu_provider:
        class: WMC\MenuPartBundle\Menu\MenuProvider
        arguments:
            - "@knp_menu.factory"
        tags:
          - { name: knp_menu.provider }

    wmc.menu_part.filter.security:
        class: WMC\MenuPartBundle\Visitor\SecurityFilterVisitor
        arguments:
           - @kernel
           - @security.access_listener
           - @request_stack

    wmc.menu_part.visitor.l10n:
        class: WMC\MenuPartBundle\Visitor\L10nVisitor
        arguments:
           - @translator
